function s = calculateStoichiometry(greenExGreenEm, greenExRedEm, ...
    redExRedEm, leakage, directExcitation, gamma)
% calculate the stoichiometry for a trace with the normal d coefficient
    
    s = ( ...
            greenExRedEm - ...
            (leakage * greenExGreenEm) - ...
            (directExcitation * redExRedEm) + ...
            (gamma * greenExGreenEm) ...
        ) ./ ...
        ( ...
            greenExRedEm - ...
            (leakage * greenExGreenEm) - ...
            (directExcitation * redExRedEm) + ...
            (gamma * greenExGreenEm) + ...
            redExRedEm ...
        );
end