function e = calculateFretEfficiency(greenExGreenEm, greenExRedEm, ...
    redExRedEm, leakage, directExcitation, gamma)
% calculate the fret efficiency for a trace with the normal d coefficient
    
    e = ( ...
            greenExRedEm - ...
            (leakage * greenExGreenEm) - ...
            (directExcitation * redExRedEm) ...
        ) ./ ...
        ( ...
            greenExRedEm -  ...
            (leakage * greenExGreenEm) - ...
            (directExcitation * redExRedEm) + ...
            (gamma * greenExGreenEm) ...
        );
end