function e = calculateFretEfficiencyPrime(greenExGreenEm, greenExRedEm, ...
    unused, leakage, directExcitation, gamma)
% calculate the fret efficiency for a trace with the d prime coefficient
%
% the third argument only exists to have the same calling signature as
% calculateFretEfficiency
    
    e_pr_raw = greenExRedEm ./ (greenExRedEm + greenExGreenEm);
    e = ( ...
            1 - ((1 + leakage + directExcitation) * (1 - e_pr_raw)) ...
        ) ./ ( ...
            1 - ((1 + leakage - gamma) * (1 - e_pr_raw)) ...
        );
end