function s = calculateStoichiometryPrime(greenExGreenEm, greenExRedEm, ...
    redExRedEm, leakage, directExcitation, gamma)
% calculate the stochiometry for a trace with the d prime coefficient
    
    s = ( ...
            gamma * ( ...
                greenExRedEm + ...
                ((gamma - leakage) * greenExGreenEm) ...
            ) ...
        ) ./ ( ...
            directExcitation * redExRedEm + ...
            gamma * ( ...
                redExRedEm + ...
                greenExRedEm + ...
                (gamma * greenExGreenEm) - ...
                (leakage * greenExGreenEm) ...
            ) ...
        );
end